/* empty css                      */import{a as w,S,i}from"./assets/vendor-BBSqv8W6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const q="49761325-2d6c711c31334dde327695ca9",v="https://pixabay.com/api/",P=15;async function h(e,r=1){const n={key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:P};try{return(await w.get(v,{params:n})).data}catch(o){throw console.error("Pixabay API Error:",o),o}}const c=document.querySelector(".gallery"),g=document.querySelector(".loader");let R=new S(".gallery a",{captionsData:"alt",captionDelay:250});function L(e,r=!1){const n=e.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img class="gallery-img" src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <ul class="info-list">
        <li class="info-item">Likes:<span> ${o.likes}</span></li>
        <li class="info-item">Views:<span> ${o.views}</span></li>
        <li class="info-item">Comments:<span> ${o.comments}</span></li>
        <li class="info-item">Downloads:<span> ${o.downloads}</span></li>
      </ul>
    </li>`).join("");r?c.insertAdjacentHTML("beforeend",n):c.innerHTML=n,R.refresh()}function y(){c.innerHTML=""}function b(){g.classList.add("visible")}function u(){g.classList.remove("visible")}function E(){const e=document.querySelector(".btn-more");e&&(e.style.display="block")}function m(){const e=document.querySelector(".btn-more");e&&(e.style.display="none")}const p=document.querySelector(".form"),M=document.querySelector(".btn-more");document.querySelector(".loader");let a=1,d="",f=0;m();p.addEventListener("submit",async e=>{e.preventDefault();const r=p.elements["search-text"].value.trim();if(d=r,a=1,f=0,m(),y(),b(),!r){i.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"}),u();return}try{const n=await h(d,a);if(f=n.totalHits,n.hits.length===0){i.info({title:"No results",message:"Sorry, nothing found for your query.",position:"topRight"}),y();return}L(n.hits),n.hits.length===15&&n.totalHits>15&&E()}catch{i.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{u()}});M.addEventListener("click",async()=>{a+=1,b();try{const e=await h(d,a);L(e.hits,!0),A(),document.querySelectorAll(".gallery-item").length>=f&&(m(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({title:"Error",message:"Failed to load more",position:"topRight"})}finally{u()}});function A(){const e=document.querySelector(".gallery-item");if(!e)return;const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
