/* empty css                      */import{a as w,S,i as n}from"./assets/vendor-BBSqv8W6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const c of i.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function t(e){if(e.ep)return;e.ep=!0;const i=o(e);fetch(e.href,i)}})();const v="49761325-2d6c711c31334dde327695ca9",P="https://pixabay.com/api/",q=15;async function h(s,r=1){const o={key:v,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:q};try{return(await w.get(P,{params:o})).data}catch(t){throw console.error("Pixabay API Error:",t),t}}const u=document.querySelector(".gallery"),g=document.querySelector(".loader");let R=new S(".gallery a",{captionsData:"alt",captionDelay:250});function L(s,r=!1){const o=s.map(t=>`
    <li class="gallery-item">
      <a href="${t.largeImageURL}">
        <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" />
      </a>
      <ul class="info-list">
        <li class="info-item">Likes:<span> ${t.likes}</span></li>
        <li class="info-item">Views:<span> ${t.views}</span></li>
        <li class="info-item">Comments:<span> ${t.comments}</span></li>
        <li class="info-item">Downloads:<span> ${t.downloads}</span></li>
      </ul>
    </li>`).join("");r?u.insertAdjacentHTML("beforeend",o):u.innerHTML=o,R.refresh()}function p(){u.innerHTML=""}function b(){g.classList.add("visible")}function d(){g.classList.remove("visible")}const m=document.querySelector(".form"),a=document.querySelector(".btn-more");document.querySelector(".loader");let l=1,f="",y=0;a.style.display="none";m.addEventListener("submit",async s=>{s.preventDefault();const r=m.elements["search-text"].value.trim();if(f=r,l=1,y=0,a.style.display="none",p(),b(),!r){n.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"}),d();return}try{const o=await h(f,l);if(y=o.totalHits,o.hits.length===0){n.info({title:"No results",message:"Sorry, nothing found for your query.",position:"topRight"}),p();return}L(o.hits),o.hits.length===15&&o.totalHits>15&&(a.style.display="block")}catch{n.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{d()}});a.addEventListener("click",async()=>{l+=1,b();try{const s=await h(f,l);L(s.hits,!0),E(),document.querySelectorAll(".gallery-item").length>=y&&(a.style.display="none",n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({title:"Error",message:"Failed to load more",position:"topRight"})}finally{d()}});function E(){const s=document.querySelector(".gallery-item");if(!s)return;const{height:r}=s.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
