/* empty css                      */import{a as b,S as w,i as a}from"./assets/vendor-BBSqv8W6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const u of i.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&t(u)}).observe(document,{childList:!0,subtree:!0});function s(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function t(e){if(e.ep)return;e.ep=!0;const i=s(e);fetch(e.href,i)}})();const P="49761325-2d6c711c31334dde327695ca9",v="https://pixabay.com/api/",S=15;async function m(o,r=1){const s={key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:S};try{return(await b.get(v,{params:s})).data}catch(t){throw console.error("Pixabay API Error:",t),t}}const d=document.querySelector(".gallery"),h=document.querySelector(".loader");let q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function g(o,r=!1){const s=o.map(t=>`
    <li class="gallery-item">
      <a href="${t.largeImageURL}">
        <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" />
      </a>
      <ul class="info-list">
        <li class="info-item">Likes:<span> ${t.likes}</span></li>
        <li class="info-item">Views:<span> ${t.views}</span></li>
        <li class="info-item">Comments:<span> ${t.comments}</span></li>
        <li class="info-item">Downloads:<span> ${t.downloads}</span></li>
      </ul>
    </li>`).join("");r?d.insertAdjacentHTML("beforeend",s):d.innerHTML=s,q.refresh()}function E(){d.innerHTML=""}function L(){h.classList.add("visible")}function f(){h.classList.remove("visible")}const p=document.querySelector(".form"),l=document.querySelector(".btn-more");document.querySelector(".loader");let n=1,y="",c=0;l.style.display="none";p.addEventListener("submit",async o=>{o.preventDefault();const r=p.elements["search-text"].value.trim();if(y=r,n=1,c=0,l.style.display="none",E(),L(),!r){a.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"}),f();return}try{const s=await m(y,n);if(c=s.totalHits,s.hits.length===0){a.info({title:"No results",message:"Sorry, nothing found for your query.",position:"topRight"});return}g(s.hits),c>n*15&&(l.style.display="block")}catch{a.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}finally{f()}});l.addEventListener("click",async()=>{n+=1,L();try{const o=await m(y,n);g(o.hits,!0),R();const r=Math.ceil(c/15);n>=r&&(l.style.display="none",a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.error({title:"Error",message:"Failed to load more"})}finally{f()}});function R(){const{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
